### ISSUE TITLE
How to set size of the draggable circle

### ISSUE THREAD

**Issue by fermatijoe** [syedowaisali/crystal-range-seekbar#11]
Hello, my seekbar is pretty small and the draggable circle is too big. I see no attributes to change the radius. Can it be done?

Thanks.

**Comment by masza** [comment]
You must do some changes inside library. You must change dimens.xml file.

**Comment by glureau** [comment]
Changing file in the library means the library is not good enough (yet ;) ).
This ticket should probably be considered as a feature request (I've the same need).

**Comment by masza** [comment]
Of course that lib is not good enough but I try to use it in my project and I find that solution so I share it ;)

**Comment by glureau** [comment]
@masza It's not about your comment, my message was just to poke @syedowaisali and request this feature as a basical usage requirement :)

**Comment by glureau** [comment]
@syedowaisali 'closed' means it won't happen?

**Comment by bgenchel** [comment]
where in the directory structure can I find the lib so I can change dimens.xml?

**Comment by bgenchel** [comment]
how do you keep the changed dimen values from being overwritten when the library is generated?

**Comment by kirvis250** [comment]
You can override dimen values by defining them in your app. But only if you redefine in all available value-<something> folders.
