### ISSUE TITLE
Reset range seekbar

### ISSUE THREAD

**Issue by gokul1408** [syedowaisali/crystal-range-seekbar#119]
how to reset rangeseekbar when a button is clicked, both pointer location should be in the default postion

**Comment by roelvandun** [comment]
rangeSeekbar.setMinStartValue(minValue);
rangeSeekbar.setMinValue(minValue);
rangeSeekbar.setMaxStartValue(maxValue);
rangeSeekbar.setMaxValue(maxValue);

**Comment by gokul1408** [comment]
rangeSeekbar.setMinStartValue(minValue).apply();
works.

**Comment by ajaydhadhal1111** [comment]
Thanks it works.
