### ISSUE TITLE
jCenter repository is deprecated - Alternative post to MavenCentral or other package repository

### ISSUE THREAD

**Issue by carlos-mg89** [syedowaisali/crystal-range-seekbar#162]
Hi!

I'm trying to update my app to the recent (not so recent actually) deprecation of jcenter repository.

After removing jcenter, I found out that this package (crystalrangeseekbar) cannot be found in any of the follow Maven repositories:
```
google()
mavenCentral()
maven { url "https://oss.sonatype.org/content/groups/public/" }
maven { url 'https://maven.google.com/' }
maven { url 'https://jitpack.io' }
```

Would it be possible to fix this situation please?

Thanks in advance

**Comment by ptsiogas** [comment]
Is this library supported?

**Comment by carlos-mg89** [comment]
@ptsiogas I fixed it by using the Github Maven repository (I think they have a repository, otherwise, Gradle seems to be compatible with it somehow):

`implementation 'com.github.syedowaisali:crystal-range-seekbar:77d3cc9994'`

Basically, with this you get the latest commit (if the latest commit doesn't change, which is most likely the case).
