### ISSUE TITLE
Change bar value  programatically

### ISSUE THREAD

**Issue by vanillazz** [syedowaisali/crystal-range-seekbar#17]
How to change bar value programatically.. ?
Cant find the setValue method..
all i find just setMinValue, setMinStartValue & setMaxStartValue...

**Comment by mladenbabic** [comment]
I have the same problem. Any feedback from author?

**Comment by syedowaisali** [comment]
You can change bar value programatically using

`seekbar.setMinStartValue(float minValue).apply();`

`rangeSeekbar.setMinStartValue(float minValue).setMaxStartValue(float maxValue).apply();`

**Comment by qindachang** [comment]
This is awsome library. I suggest to support databinding in some attributeSet or @BindingAdapter

**Comment by GastricSpark** [comment]
The library is really nice, would suggest that you add a sample project to it though so people know how to use it. Took me ages to realise I needed to add .apply();

**Comment by ryust** [comment]
I don't think this is working as stated by the owner. Please see my comment on issue #24. Are others able to set min and max start values successfully at the same time?

**Comment by ryust** [comment]
It appears my issue was fixed in 1.1.3 version.

**Comment by OriginApp-Shri** [comment]
Hi, I have two thumb drawable with fix_gap =3. Programmatically I need to set value to those thumbs. Please let me know how to set two different values for two thumbs.

**Comment by comm1x** [comment]
How to change value from code? I have wondered that there is no setter for this obvious method?

**Comment by Bajranghudda** [comment]
Its working fine

**Comment by MohammedShehata** [comment]
> `setMinStartValue(float minValue).setMaxStartValue(float maxValue).apply();`

The view is freezed, and the values aren't changed and also can't change it manually.
Any Help!
Thanks!
