### ISSUE TITLE
how to reset min and  max values in crystal seekbar

### ISSUE THREAD

**Issue by saffull** [syedowaisali/crystal-range-seekbar#19]
hello, how can i reset the min value and max value in seekbar, i tried
 .setValue, but is there any other way..?

**Comment by syedowaisali** [comment]
You can change bar value programatically using

rangeSeekbar.setMinStartValue(float minValue).setMaxStartValue(float maxValue).apply();

**Comment by imarenco** [comment]
thnks! @syedowaisali

**Comment by bgenchel** [comment]
@syedowaisali that does not work for me. It just puts the start and end at the same position.

**Comment by imarenco** [comment]
Hello @bgenchel. I use this example in my code, and work:
` 
   CrystalRangeSeekbar rangeSeekbar = (CrystalRangeSeekbar) findViewById(R.id.range);
    rangeSeekbar.setMinValue(1920);
    rangeSeekbar.setMaxValue(2016); 
    rangeSeekbar.setMinStartValue(min).setMaxStartValue(max).apply();
`

Make sure to set .apply() for see changes.

**Comment by bgenchel** [comment]
@imarenco yup, apply is key, but just for other people that happen upon this question: even with apply(), I did not see the behavior that I wanted. It would push both to only one value or both to the front. Weird stuff.

It was only after I switched to version 1.1.3 of the library did I get any combination of these commands to work.

**Comment by mack369** [comment]
there is a new problem #33 in 1.1.3 

It doesn't work if the values are near to the top

**Comment by Gkundu1** [comment]
Any kind of method is there to change the seek the position of the left thumb and the right thumb but also the same not to change the min value and max value for left and right thumb respectively.
The purpose is that already having left and right seek position but at the same time don't want to change the min value and max value of seek bar.

**Comment by syedowaisali** [comment]
fixed in upcoming version.

**Comment by sanjeevcharan** [comment]
Hi,
rangeSeekbar.setMaxStartValue(20) is working fine.But there is failure in minstartvalue(), when i tried to set 
rangeSeekbar.setMaxStartValue(6) but it setting to 12.please reply me as fast as possible.
Thanks

**Comment by alishaker** [comment]
Hello,

Any update about @sanjeevcharan issue, i facing same issue, i set the minValue to 14, but when i try to get the minValue it gives me 4
