### ISSUE TITLE
setMaxStartValue and setMinStartValue not working programmatically 

### ISSUE THREAD

**Issue by Kostya1375** [syedowaisali/crystal-range-seekbar#2]
Trying to set minStartValue and maxStartValue programmatically  get them set to min and max values.
`rangeSeekBar
                .setMinStartValue(ageMin)
                .setMaxStartValue(ageMax)
                .apply();`

**Comment by syedowaisali** [comment]
Bug fixed. you can use latest version of library 1.0.1

**Comment by janammaharjan** [comment]
while setting minimum start value the seekbar behaves weirdly. Both the thumbs(max and min) set in same place.

**Comment by codenamesid** [comment]
Any solution for this problem?
