### ISSUE TITLE
Feature request: auto-attract

### ISSUE THREAD

**Issue by glureau** [syedowaisali/crystal-range-seekbar#20]
If used in a short range (1-10 for example), the bar should be visually discrete.
The current values are right but the cursors should be attract by the real values or it ends up with visual range but min=max.

![image](https://cloud.githubusercontent.com/assets/7968075/20382918/1fb34f4a-acae-11e6-80c6-d6f76decb491.png)

**Comment by syedowaisali** [comment]
fixed in upcoming version.
