### ISSUE TITLE
Setting min & max start value

### ISSUE THREAD

**Issue by StobieC** [syedowaisali/crystal-range-seekbar#24]
When I set both the min and max start values it sets both thumbs to the lowest values that I've defined in setMaxValue() and setMinValue(). However when I set only the min start value or max start value using setMinStartValue() or setMaxStartValue() it works as expected.

**Comment by ryust** [comment]
The comment above seems a big confusing, but I think I may be encountering the same problem.

I have a range seekbar with two thumbs. You can programmatically set the min or max start values individually, but the action will always put both thumbs at the same value. For example, if you issue setMinStartValue(), it sets both min and max values (with the thumbs) at that min value. If you issue, setMaxStartValue() by itself, it sets both to the max value.

Therefore, issuing mRangeSeekbar.setMinStart(x).setMaxStartValue(y).apply() results in both thumbs residing on top of each other at x.

**Comment by ryust** [comment]
It appears version 1.1.3 fixes the issue I had and now both min/max start values can be set correctly.

**Comment by gfdarcy** [comment]
I am having an issue setting both min and max, like this;
       PriceRange.setMinStartValue(40).apply();
       PriceRange.setMaxStartValue(120).apply();

Max works fine.

Min, however, has problems, as follows;
1. the min range (MinValue) changes to 0 (it was previously 20). 
2. The selected min value changes to 0, not 40.

**Comment by Gkundu1** [comment]
The suggestion of @ryust does work fine.The bug got resolved for the version 1.1.3

**Comment by nzackoya** [comment]
setMaxStartValue is missing
