### ISSUE TITLE
how to apply onStopTrackingTouch() in crystal range seekbar?

### ISSUE THREAD

**Issue by janammaharjan** [syedowaisali/crystal-range-seekbar#3]
I need to track the final value of the range seekbar after user takes a finger out of the range bar. Normal seekbars have onStopTrackingTouch mode for it, but how do i do it using crystal range seekbar?

**Comment by syedowaisali** [comment]
## Range Seekbar
Two way to getting `Min` and `Max` value.

**1.** You can implement listener
```java
// get seekbar from view
final CrystalRangeSeekbar rangeSeekbar = (CrystalRangeSeekbar) findViewById(R.id.rangeSeekbar1);

// get min and max text view
final TextView tvMin = (TextView) findViewById(R.id.textMin1);
final TextView tvMax = (TextView) findViewById(R.id.textMax1);

// set listener
rangeSeekbar.setOnRangeSeekbarChangeListener(new OnRangeSeekbarChangeListener() {
    @Override
    public void valueChanged(Number minValue, Number maxValue) {
        tvMin.setText(String.valueOf(minValue));
        tvMax.setText(String.valueOf(maxValue));
    }
});
```

**2.** Get values direct from range seekbar.
```
rangeSeekbar.getSelectedMinValue();
rangeSeekbar.getSelectedMaxValue();
```

**Comment by janammaharjan** [comment]
@syedowaisali I need the values right after the user is done sliding the rangeseekbar as I have to call an api to process the values. Right now, I have placed the api call inside valueChanged which calls the api with every change in seekbar causing overload of data. Is there any way to get onStopTrackingMode working in CryastalRangeSeekBar?

**Comment by syedowaisali** [comment]
feature added in updated version kindly update your version.

```compile 'com.crystal:crystalrangeseekbar:1.0.1'```
```Change to```
```compile 'com.crystal:crystalrangeseekbar:1.1.1'```

```
// set final value listener
rangeSeekbar.setOnRangeSeekbarFinalValueListener(new OnRangeSeekbarFinalValueListener() {
    @Override
    public void finalValue(Number minValue, Number maxValue) {
        Log.d("TAG", String.valueOf(minValue) + " : " + String.valueOf(maxValue));
    }
});
````

**Comment by kunjanrshah** [comment]
I used crystalSeekbar in my project. i am stuck like I want to functionality like **normal seek bar** if user click any where on seek **bar** (not on thumb icon) thumb icon will place at that place. user no need to drag thumb icon

Thanks in Advance
