### ISSUE TITLE
setMinStartValue and setMaxStartValue do not work properly for CrystalRangeSeekbar (new problem!)

### ISSUE THREAD

**Issue by artests87** [syedowaisali/crystal-range-seekbar#33]
Hi!
1.1.3
If I set the minValue near the maxValue(end bar) - I get minValue and maxValue at the start bar, instead minValue and maxValue at the end bar.
Thanks

**Comment by mack369** [comment]
I have the same issue

**Comment by gfdarcy** [comment]
Ditto. 1.1.3 installed. 
(Gap also doesn't work, but I'll mention that elsewhere)

**Comment by TheLester** [comment]
Same issue. I noticed that problem only when i set min/max start value programatically

**Comment by stangabogdan** [comment]
Fixed it. Waiting for the pull request #49 to be merged.
