### ISSUE TITLE
Thumb image getting clipped

### ISSUE THREAD

**Issue by ikermart** [syedowaisali/crystal-range-seekbar#35]
When I press the thumb, the image getting clipped, where can we change the seekbar height area?

**Comment by wjsm93** [comment]
I'm having the same issue:

![captura de pantalla 2017-01-25 a las 5 37 31 p m](https://cloud.githubusercontent.com/assets/16049195/22310275/2181641c-e325-11e6-8fff-a6c57c56fc28.png)

**Comment by qbai22** [comment]
+

**Comment by qbai22** [comment]
same

**Comment by kucheech** [comment]
try using android:clipChildren="false" in the parent container xml

**Comment by ajpetrizza** [comment]
kucheech has the correct answer :) Thank you sir!
