### ISSUE TITLE
Click on seekbar to change value without using thumb

### ISSUE THREAD

**Issue by apjx** [syedowaisali/crystal-range-seekbar#36]
Hi,

Many people start using a seekbar without using the thumb, they just click anywhere on the seekbar then move the thumb if necessary.
Currently nothing happens when I click on my crystal seekbar. Is it possible to activate the clicks on the seekbar ?

**Comment by syedowaisali** [comment]
not supported, you feature has been noted and it will be available in next release.
Thanks

**Comment by jesusmartinoza** [comment]
This feature is on master but not in maven
https://github.com/syedowaisali/crystal-range-seekbar/pull/74

**Comment by apjx** [comment]
Hi there,

Can you tell me how to use 'master" ?

I currently get the following error message :
error: attribute 'com.myapp.android:seek_bar_touch_enabled' not found.


Alexandre Ploujoux
06 64 73 75 55

2018-06-29 20:29 GMT+02:00 Jesús Alberto Martínez Mendoza <
notifications@github.com>:
