### ISSUE TITLE
More control over steps?

### ISSUE THREAD

**Issue by gfdarcy** [syedowaisali/crystal-range-seekbar#41]
Hi,
Is it possible to explicitly set the Steps?
I am doing an age range using your CrystalRangeSeekbar. My min is 18, max 100. I'd like the steps to be;
18, 20, 25, 30....[then in 5s]...95, 100. 
Thanks a lot!

**Comment by raghunandankavi2010** [comment]
I did something similar by building on top of the existing awesome work done by the author. Pls check https://github.com/raghunandankavi2010/SamplesAndroid/tree/master/FreeLanceProject if it helps. I can create a PR if its good. This is just a naive implementation and needs little bit of work to get it right.
