### ISSUE TITLE
thumb_image from GradientDrawable

### ISSUE THREAD

**Issue by pro100svitlo** [syedowaisali/crystal-range-seekbar#47]
Hi!

please add possibility to set GradientDrawable to thumb_image.
for example it is much easier to me draw thumbs  as shape drawables, than draw images via gimp

**Comment by rambabusaravanan** [comment]
Yes, I'm also waiting for drawables xml.
I'm getting the following error when using drawable xml as thumb image

ClassCastException: android.graphics.drawable.GradientDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

**Comment by syedowaisali** [comment]
not supported yet, but it will be available asap.
