### ISSUE TITLE
How set initial value to craystal seekbar from code ?

### ISSUE THREAD

**Issue by mahmooddagga** [syedowaisali/crystal-range-seekbar#5]
How set initial value to craystal seekbar from code ?

**Comment by mahmooddagga** [comment]
@syedowaisali

**Comment by mahmooddagga** [comment]
how get current progress value????

**Comment by junaid-umar** [comment]
setMinStartValue is there but not working ...

**Comment by mahmooddagga** [comment]
oh , thanks @junaid-umar  ,, do you know  how to get current progress value????

**Comment by junaid-umar** [comment]
use SeekbarChangeListener.

**Comment by junaid-umar** [comment]
initial value can be set from xml only..i think ...thinking to change lib

**Comment by syedowaisali** [comment]
initial value can be set from xml or java.

XML
```
<com.crystal.crystalrangeseekbar.widgets.CrystalSeekbar
    android:id="@+id/seekbar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:min_value="0"
    app:max_value="100"/>
```

JAVA
```
// get seekbar from view
final CrystalSeekbar rangeSeekbar = (CrystalSeekbar) rootView.findViewById(R.id.seekbar);

// change position left to right
rangeSeekbar.setMinValue(0).setMaxValue(100).apply();
```

**Comment by mahmooddagga** [comment]
what about get current progress value ?

and thanks

**Comment by syedowaisali** [comment]
There are three ways to get current progress value.

- 1 get min value rangeSeekbar.getSelectedMinValue(); and get max value rangeSeekbar.getSelectedMaxValue();

- 2  Attach listener to get updated current value.
```
rangeSeekbar.setOnRangeSeekbarChangeListener(new OnRangeSeekbarChangeListener() {
    @Override
    public void valueChanged(Number minValue, Number maxValue) {
        Log.d("CRS=>", String.valueOf(minValue) + " : " + String.valueOf(maxValue));
    }
});
```

- 3 Attach listener to get final value
````
rangeSeekbar.setOnRangeSeekbarFinalValueListener(new OnRangeSeekbarFinalValueListener() {
    @Override
    public void finalValue(Number minValue, Number maxValue) {
        Log.d("CRS=>", String.valueOf(minValue) + " : " + String.valueOf(maxValue));
    }
});
````

**Comment by vandatqb** [comment]
How can i set min start and max start vlue, i have try use : 
rangeSeekbar.setMinStartValue(valueMin);
rangeSeekbar.setMinValue(valueMax);
rangeSeekbar.apply();
but it not work !

**Comment by agueroveraalvaro** [comment]
> setMinStartValue is there but not working ...

Try

To set progress
        ```
mRangeSeekbar.setMinStartValue(100);
        mRangeSeekbar.setMaxStartValue(100);
        **mRangeSeekbar.apply();**
```
