### ISSUE TITLE
where is the method ? crySeekBar.setCurrentPosition( ) ? 

### ISSUE THREAD

**Issue by OOOOOldZhu** [syedowaisali/crystal-range-seekbar#50]
where is the method ? crySeekBar.setCurrentPosition( ) ? i want a method to set the seekbar current position . fix your class please .

**Comment by OOOOOldZhu** [comment]
where is the method ? crySeekBar.setCurrentPosition( ) ?

**Comment by rohitshampur** [comment]
#51 Check the second comment from this issue
