### ISSUE TITLE
How to set setProgress for Min and Max value in progress bar?

### ISSUE THREAD

**Issue by kjanagiram** [syedowaisali/crystal-range-seekbar#51]
I am using seekbar  with two side thumb. I am changing min and max value and viewing result in another activity. Once I returned to that seekbar activity I want to show the last selected min and max value in seekbar. How can I achieve this one? I unable to find setProgress method for Min and Max value respectively.

**Comment by rohitshampur** [comment]
save the min and max value and set the max and min value when you return to the seekbar activity like below
```
mCrystalRangeSeekBar.setMinStartValue(min);
mCrystalRangeSeekBar.setMaxStartValue(max);
mCrystalRangeSeekBar.apply();//this is important
```

**Comment by awfatech** [comment]
@rohitshampur Please use this to set current position.
crySeekBar.setMinStartValue(val);
crySeekBar.apply();//this is important
