### ISSUE TITLE
setminStartValue not working properly

### ISSUE THREAD

**Issue by anuj7sharma** [syedowaisali/crystal-range-seekbar#60]
If I'm trying to use `setMinStartValue(1735f).apply();` then seekbar is pointing at position 17.
Its not taking start thumb to exact that point.

Please fix this issue.

**Comment by SeaRoth** [comment]
My bar goes from 0-100

I got it to work by using .apply

e.g.

sbJpegQuality.setMinStartValue(99f);
sbJpegQuality.apply();

**Comment by StolarczykJakub** [comment]
Same here. 
The solution for this is
setMinStartValue(1735f);
setMaxStartValue(2323f).apply();

You have allways set Min and max, and then apply.

**Comment by GilbertKiwanPark** [comment]
update latest version. it doesn't work 1.0.0

at 2018.1.25 the latest version is
compile 'com.crystal:crystalrangeseekbar:1.1.3'
