### ISSUE TITLE
how can i make the textview move with the thumb?

### ISSUE THREAD

**Issue by xxwn446** [syedowaisali/crystal-range-seekbar#61]
i want to know how can i make the textview move with the thumb

**Comment by xxwn446** [comment]
who can help me?thanks very much

**Comment by daesu** [comment]
@xxwn446 
Not an efficient solution but this is what I'm doing. 

Get the x coordinates of the thumbnail Rect with;

`crystalSeekBar.getLeftThumbRect().left;`

This value will allow you to align the Left coordinates of your TextView with the Left coordinates of the bounds of the thumb. 

`TextView.setX(crystalSeekBar.getLeftThumbRect().left));`

**Comment by xxwn446** [comment]
thank you very much!!!


------------------ 原始邮件 ------------------
发件人: "Pól Ó Riain";<notifications@github.com>;
发送时间: 2017年8月9日(星期三) 下午4:30
收件人: "syedowaisali/crystal-range-seekbar"<crystal-range-seekbar@noreply.github.com>; 
抄送: "___陌 离"<1003860152@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [syedowaisali/crystal-range-seekbar] how can i make the textviewmove with the thumb? (#61)




@xxwn446
 Not an efficient solution but this is what I'm doing.
 
Get the x coordinates of the thumbnail Rect with;
 
crystalSeekBar.getLeftThumbRect().left;
 
This value will allow you to align the Left coordinates of your TextView with the Left coordinates of the bounds of the thumb.
 
TextView.setX(crystalSeekBar.getLeftThumbRect().left));

**Comment by lucasharada** [comment]
@daesu Didn't work for me. My `crystalSeekBar` object doesn't have `getLeftThumbRect` method.

**Comment by daesu** [comment]
@lucasharada It's a method I am seeing in crystalSeekBar.java. You can see it here ; https://github.com/syedowaisali/crystal-range-seekbar/blob/master/crystalrangeseekbar/src/main/java/com/crystal/crystalrangeseekbar/widgets/CrystalSeekbar.java on L287

**Comment by lucasharada** [comment]
@daesu Weird. I'm getting this error:
> Error:(130, 33) error: getLeftThumbRect() has protected access in CrystalRangeSeekbar

I'm using the latest version available (v 1.1.1) as included below:
`compile 'com.crystal:crystalrangeseekbar:1.1.1'`

**Comment by daesu** [comment]
@lucasharada You are looking at the Crystal**Range**Seekbar.java file, not CrystalSeekbar.java. 

The Crystal**Range**Seekbar is for selecting a range of values, the CrystalSeekbar only has one thumb. In Crysta**lRange**Seekbar the getLeftThumbRect() method is protected but in CrystalSeekbar the getLeftThumbRect() method is public.

**Comment by lucasharada** [comment]
@daesu Oh, I get it. This won't work for me, but thanks anyway!
