### ISSUE TITLE
How to change left and right bar_color ? 

### ISSUE THREAD

**Issue by chathudan** [syedowaisali/crystal-range-seekbar#64]
How can I change bar color like this?

![seekbar](https://user-images.githubusercontent.com/3352653/31071887-6a1dd5d4-a783-11e7-8ef9-6828f6c42ebc.png)

**Comment by msayanece** [comment]
app:left_thumb_color="@color/colorAccent"
        app:left_thumb_color_pressed="@color/colorAccent"
        app:right_thumb_color="@color/colorAccent"
        app:right_thumb_color_pressed="@color/colorAccent"

**Comment by syedowaisali** [comment]
Not supported yet, 
The feature noted and it will be supported on next version that will be available soon.
