### ISSUE TITLE
the jcenter version 1.1.3 is not the newest code version

### ISSUE THREAD

**Issue by fan123199** [syedowaisali/crystal-range-seekbar#68]
In the newest version ,it  fix a getBarHeight bug in apply() , but when i use jcenter dependency , it is not fixed.   in the jcenter, the code is 

```
barHeight = (thumbHeight * 0.5f) * 0.3f;
```

In github:

https://github.com/syedowaisali/crystal-range-seekbar/blob/3d4bd414f23c44c125cd10d2b3490879941f97e9/crystalrangeseekbar/src/main/java/com/crystal/crystalrangeseekbar/widgets/CrystalRangeSeekbar.java#L478

**Comment by alenz316** [comment]
Ditto
