### ISSUE TITLE
max_start_value property not working at design time

### ISSUE THREAD

**Issue by cs-abdulwahab** [syedowaisali/crystal-range-seekbar#69]
max_start_value property not working at design time

if min_start_value is mentioned   max_start_value is by default equal to min_start_value

**Comment by reyanshmishra** [comment]
Yeah same here.

**Comment by mattstanford** [comment]
Hi,

Why was this issue closed?  This issue still exists.  Setting the `min_start_value` and `max_start_value` together in XML still causes the `max_start_value` to be set incorrectly.
