### ISSUE TITLE
How to set default value or set thumb to the specific value

### ISSUE THREAD

**Issue by aashirjaved** [syedowaisali/crystal-range-seekbar#7]
I want to set the thumb to the last saved value is that possible?

**Comment by syedowaisali** [comment]
```
final CrystalRangeSeekbar rangeSeekbar = (CrystalRangeSeekbar) findViewById(R.id.seekbar);
rangeSeekbar.setMinStartValue(20).setMaxStartValue(80).apply();
```

**Comment by abhishek158** [comment]
But this not work.

**Comment by sousav** [comment]
Still not working, Will you update it?

**Comment by AndroidDeveloper3** [comment]
not working @syedowaisali  will you update it.

**Comment by aniltiwari1402** [comment]
Hey, I've configured range seek bar in my app, It is working fine, I am able to set default minimum and maximum values to the seek bar as well. Also it is taking the new minimum and max values (i.e. range, dynamically) But I want to set this value (new min/max value) to the activity so that it should indicate the last value that I've selected.

**Comment by AndroidDeveloper3** [comment]
For that use Shared Preference,
put below code before OnrangeSeekbarChangeListener,
SharedPreferences sp = getSharedPreferences("MinMax", Context.MODE_PRIVATE);
        int min = sp.getInt("min", 0);
        int max = sp.getInt("max", 0);
        rangeSeekBar.setSelectedMinValue(min);
        rangeSeekBar.setSelectedMaxValue(max);

ANd Put below code in SeekBarChangeListener()
SharedPreferences sp = getSharedPreferences("MinMax", Context.MODE_PRIVATE);
                SharedPreferences.Editor spe = sp.edit();
                spe.putInt("min", (Integer) minValue);
                spe.putInt("max", (Integer) maxValue);
                spe.commit();

with this, when you are changing values dynamically, it will save in sharedPreference and when you starts the application, it will you previously selected values on seekbar.

**Comment by FuatBA** [comment]
Hi  @abhishek158,

 If you want to set initial value to seek bar. You shoult write this code:
  seekbar.setMinStartValue(50);
 **seekbar.apply();**

**Comment by vijayneosoft** [comment]
how to move above text value with crystalrangeseekbar thumb

**Comment by bhavikmehta5491** [comment]
The logic is save minUserSelected value somewhere
and do seekbar.setMinStartValue(minUserSelected).apply();

seekbar.apply();

**Comment by Dilip-lohar** [comment]
```
    rangeSeekbar.setMinStartValue(min) ;
    rangeSeekbar.setMaxStartValue(max);
    rangeSeekbar.apply();
```
