### ISSUE TITLE
Move one end at a time

### ISSUE THREAD

**Issue by achinverma** [syedowaisali/crystal-range-seekbar#72]
Hi i am using this library for seekbar and i am using below type
https://camo.githubusercontent.com/b3bf56e3993a509e9da444932aef57e08b7efb88/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d766965772669643d3042396244454e794941425436626e5a4a57565a7755475636544763

now , in this we can move both ends at a time, but my requirement is move one end at a time, i don't want to move both ends at same time

or any listener which detect both ends are moving so we can stop to move?

**Comment by syedowaisali** [comment]
Not supported on this version.
Your request has been noted and it will be available as soon as possible.
Thanks

**Comment by YudizVinay** [comment]
Is it available now?
