### ISSUE TITLE
How to set a range like 15-40 in crystal range seekbar onload?

### ISSUE THREAD

**Issue by jerin6392** [syedowaisali/crystal-range-seekbar#75]

**Comment by Findsen** [comment]
Not sure if this is what you are looking for, as your description isnt that good.
mySeekbar.setMinStartValue(15).setMaxValue(40).apply();

**Comment by jerin6392** [comment]
I want to set left thumb to 15 and right thumb to 40 initially with 0-100 range.

**Comment by Findsen** [comment]
The above line should do the trick for you.

**Comment by jerin6392** [comment]
Its not working.

**Comment by Findsen** [comment]
Could you post some code ?

**Comment by rushilMethsof** [comment]
facing this issue 
rangeSeekbar.setMinStartValue(20.0f).setMaxStartValue(40.0f).apply(); 
is not doing the job for the range (0 - 100)

**Comment by rushilMethsof** [comment]
My bad , seems to be working in version 1.1.3
