### ISSUE TITLE
Like normal seek bar if user click any where on seek bar (not on thumb icon) thumb icon will place at that place. user no need to drag thumb icon

### ISSUE THREAD

**Issue by kunjanrshah** [syedowaisali/crystal-range-seekbar#76]
I used crystalSeekbar in my project. i am stuck like I want to functionality like **normal seek bar** if user click any where on seek **bar** (not on thumb icon) thumb icon will place at that place. user no need to drag thumb icon
Thanks in Advance

**Comment by syedowaisali** [comment]
Regrets, not supported on this version.
this is what you looking for in next version.
Launching Soon.
