### ISSUE TITLE
CrystalSeekbar no thumb_image attribute

### ISSUE THREAD

**Issue by BROUDING** [syedowaisali/crystal-range-seekbar#77]
I'm using 1.1.3, (Loved using RangeSeekbar before btw)

I'd love to commit this bug,
I don't have time to contribute right at the moment...

Issue : When using CrystalSeekbar, there is no `thumb_image` attribute.
For now : Use `left_thumb_image` attribute.

**Comment by syedowaisali** [comment]
I am sorry, you having a lot of trouble.

I am working on the upgrade version of Seekbar.

Launching Soon.
