### ISSUE TITLE
Cannot set custom thumb XML drawable

### ISSUE THREAD

**Issue by SebSob** [syedowaisali/crystal-range-seekbar#79]
**Type**:
CrystalRangeSeekbar

**Problem**
Can't set a custom .xml thumb drawable. (Problem for both XML as Java)

**Code**
```
rangeSeekBar = findViewById(R.id.rangeSeekBar);
rangeSeekBar.setLeftThumbDrawable(R.drawable.custom_rangeseekbar_thumb);
```

**Error log**
`Caused by: java.lang.ClassCastException: android.graphics.drawable.LayerDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                      at com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar.getBitmap(CrystalRangeSeekbar.java:485)`

 Any idea?

**Comment by mxl** [comment]
Duplicate of #14

**Comment by syedowaisali** [comment]
XML drawable not supported yet
