### ISSUE TITLE
how to reset the range of the left and right controller by specific value pragmatically ? 

### ISSUE THREAD

**Issue by MinaMedhatKamel** [syedowaisali/crystal-range-seekbar#81]

**Comment by syedowaisali** [comment]
Currently, there is no reset method supported alternately you can reset the position of thumbs by using these methods.

```java
rangeSeekbar
    .setMinValue(0)
    .setMinStartValue(0)
    .setMaxValue(100)
    .setMaxStartValue(100);
````

**Comment by MinaMedhatKamel** [comment]
But if we take the same example that you provide and set setminstartValue(10) it will not be worked

**Comment by MinaMedhatKamel** [comment]
Oka I just forget to use .apply() method after setting the start and end value :)
