### ISSUE TITLE
Start Values

### ISSUE THREAD

**Issue by sarantche** [syedowaisali/crystal-range-seekbar#9]
Hi, if I set CrystalRangeSeekbar like this: 

```
    CrystalRangeSeekbar seekbar = new CrystalRangeSeekbar(this);
    seekbar .setDataType(CrystalRangeSeekbar.DataType.FLOAT)
            .setMinValue(5f)
            .setMaxValue(30f)
            .setSteps(0.5f)
            .setMinStartValue(18.5f)
            .setMaxStartValue(23.0f);
```

it gives me maxStartValue equal to minStartValue, so min and max start values are both 18.5 at the end.

**Comment by MuhammadArsalanChishti** [comment]
you did not use apply method to make changes to  CrystalRangeSeekbar .
CrystalRangeSeekbar seekbar = new CrystalRangeSeekbar(this);
    seekbar .setDataType(CrystalRangeSeekbar.DataType.FLOAT)
            .setMinValue(5f)
            .setMaxValue(30f)
            .setSteps(0.5f)
            .setMinStartValue(18.5f)
            .setMaxStartValue(23.0f)
            .apply();
