### ISSUE TITLE
max_start_value is not working in CrystalRangeSeekbar

### ISSUE THREAD

**Issue by ankur-dev** [syedowaisali/crystal-range-seekbar#93]
i have set min value, max value, Now i want to set max_start_value  which is greater than min value and less than max value. but its not working.
Ex my min value is 1000 and max value is 10000, now i want to set max start value 4000.

**Comment by Bikeskin** [comment]
hi ankur-dev,
could you try it like this? 
rangebarPrice.setMinValue(1000)
                .setMaxValue(10000)
                .setMinStartValue(2000)
                .setMaxStartValue(4000)
                .apply();

**Comment by ankur-dev** [comment]
Thank you .
Its working.

**Comment by squarest** [comment]
Please, tell about it in documentation
I've spend 2 days before finding this topic

**Comment by rastogitech** [comment]
Why you designed it in a way that it needs apply(). It's really unexpected, I spent my time looking into it.

**Comment by ElectApp** [comment]
Me too! I almost change library because I spent more time for trying. I think should add example on https://github.com/syedowaisali/crystal-range-seekbar

Thank you
