### ISSUE TITLE
How can move right and left thumb_image by set value programmatically ?

### ISSUE THREAD

**Issue by ITWhiz4U** [syedowaisali/crystal-range-seekbar#98]
I need to set value and move the right and left thumb images with programmatically.
Ex: I have get the minValue and maxValue on the first page so that need to show this status on next page.
Please let me know how can do this.

Please feel free to let me know.
Thanks.

**Comment by appukrb** [comment]
Did you got solution for that?

**Comment by chigup** [comment]
anyone got solutin for that
